#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Ryuichi Ueda <Viimaple1001@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause

def day_water(weight):
    return weight * 0.033

print("体重を入力してください[単位：kg]")
try:
    weight = float(input())
    if weight <= 0:
       print("有効な体重を入力してください")
    else:
         need_water = day_water(weight)
         print(f"あなたの体重に基づき、1日に必要な水分摂取量は{need_water:.2f}Lです。")
except:
    print("無効な入力です。体重を数値で入力してください。")    
    

